### ISSUE TITLE
Supress warnings with attributes

### ISSUE THREAD

**Issue by ghost** [AlexEne/rust_hawktracer#11]
You say we should name variables with leading `_`s to avoid warnings, but when binding the identifier can't you put an [`#[allow(dead_code)]`](https://stackoverflow.com/questions/25877285/how-to-disable-unused-code-warnings-in-rust) attribute in the macro to suppress warnings?

> ## Things to watch out for
>
> In rust macros I can't create new identifier names. This means that if you want to avoid warnings, the > tracepoint names have to start with a leading _, as in scoped_tracepoint!(_my_tracepoint_name).

**Comment by AlexEne** [comment]
I think you're right. When I wrote that I didn't realize I could put `#[allow(dead_code)]` anywhere. 

It could probably just work if I add this in `lib.rs` here:
https://github.com/AlexEne/rust_hawktracer/blob/master/src/lib.rs#L17

**Comment by ghost** [comment]
On that note, I think it's also more idiomatic to move [this](https://github.com/AlexEne/rust_hawktracer/blob/bf287801c440d0a5e184f35a3aeb7166cef3f402/src/lib.rs#L1) `#[allow(dead_code)]` _inside_ the module as `#![allow(dead_code)]` (which applies to the item which contains it).

**Comment by AlexEne** [comment]
So after ages, I've came back to this, and It doesn't work no matter how many or where I add `#[allow(dead_code)]` in or near those macros.

Also the allow deadcode outside that module helps with the autogenerated bindings basically generating  a ton of warnings on unused members.

For that reason I will close this but if you know a fix for it I am happy to merge a PR
