### ISSUE TITLE
Make a new release?

### ISSUE THREAD

**Issue by lu-zero** [AlexEne/rust_hawktracer#18]
Would be nice to have 0.5 release on crates.io.

**Comment by AlexEne** [comment]
I agree, now that I added the proc macro stuff as it was a huge refactor. 

I'll make an issue where I track bugs/changes for the 0.5 release so it's a bit more clear to anyone what work is needed. In the meantime you can use the master branch in `cargo.toml`.

**Comment by AlexEne** [comment]
Addeed #19
