### ISSUE TITLE
Release v0.5

### ISSUE THREAD

**Issue by AlexEne** [AlexEne/rust_hawktracer#19]
- [x] Check that VS 2019 respects Debug/Release configurations when building. Right now there's an warning and they seem ignored.
- [ ] ~~Perf. optimization for sending tracepoints around. I need to chat to the hawktracer maintainer as he suggested a faster way to send these.~~

**Comment by lu-zero** [comment]
Currently I managed to get an assert triggered on macOS on mutex unlock, I'm not sure how easy could be to reduce the testcase properly so I can pin it to upstream hawktrace, here, or my usage of it =/

**Comment by lu-zero** [comment]
Updating the version of hawktracer in rust_hawktracer_sys made the problem go away.

**Comment by AlexEne** [comment]
I will update to the newest hawktracer (the C library) release as one happened a few days ago.

**Comment by AlexEne** [comment]
I've released a new version. https://www.crates.io/crates/rust_hawktracer

Visual studio builds just fine.  
The optimization suggestied by Marcin in #20 will be done in a later release.
Also bumped the C hawktracer library to 0.9.0

**Comment by lu-zero** [comment]
Great! Thank you!
